<?php
echo
'<section class="section-cards">',
    '<a href="./about.php#professional-career">',
        '<div class="card">',
            '<div class="content-card">',
                '<img src="./assets/pictures/logos/parcours.svg" alt="Image parcours personnel" width="100" loading="lazy">',
                '<h2>Parcours</h2>',
                '<p>Une section où vous trouverez le détaille de mon parcours professionnel.</p>',
            '</div>',
        '</div>',
    '</a>',
    '<a href="./about.php#skills">',
        '<div class="card">',
            '<div class="content-card">',
                '<img src="./assets/pictures/logos/grades.svg" alt="Image qualifications personnel" width="100" loading="lazy">',
                '<h2>Qualifications</h2>',
                '<p>Une section donnant une liste détaillée de mes compétences techniques et professionnelles.</p>',
            '</div>',
        '</div>',
    '</a>',
    '<a href="./about.php#cv" id="index-card-cv">',
        '<div class="card">',
            '<div class="content-card">',
                '<img src="./assets/pictures/logos/cv.svg" alt="Image CV" width="100" loading="lazy">',
                '<h2>Mon CV</h2>',
                '<p>Une section dédiée à mon CV. Vous pouvez le télécharger au format PDF.</p>',
            '</div>',
        '</div>',
    '</a>',
    '<a href="./portfolio.php">',
        '<div class="card">',
            '<div class="content-card">',
                '<img src="./assets/pictures/logos/projects.svg" alt="Image projets" width="100" loading="lazy">',
                '<h2>Projets livrés</h2>',
                '<p>Une page qui montre et explique mes projets web réalisés.</p>',
            '</div>',
        '</div>',
    '</a>',
'</section>';